name: coverage

on: [push]

jobs:
  coverage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Cypress
        uses: cypress-io/github-action@v5

      - name: Codecov
        uses: codecov/codecov-action@v3
